### ISSUE TITLE
Crear clase Usuario/Técnico/Empresa

### ISSUE THREAD

**Issue by RafaelMengui** [ucudal/pii_2019_equipo7#5]
Crear clase Usuario/Técnico/Empresa

**Comment by mich08639** [comment]
Se implementara la solución brindada por  Fernando en le repo:
https://github.com/fmachadopiriz/RazorPagesMovie

**Comment by mich08639** [comment]
se debe implementar un sistema de roles basado en lo que envió frenado

**Comment by mich08639** [comment]
Se realiza el mismo sistema de roles y pemrisos que implemento frenando
