### ISSUE TITLE
Crear Filtro/FiltroEmpresas/FiltroUsuarios_Asignadas

### ISSUE THREAD

**Issue by RafaelMengui** [ucudal/pii_2019_equipo7#9]
Crear Filtro/FiltroEmpresas/FiltroUsuarios_Asignadas

**Comment by SantiagoVaraldo** [comment]
Clase filtro realizada.

**Comment by mich08639** [comment]
Esta tarea no aplica de esta forma, se definira una tarea con una descripción mas apropiada para realizar los distintos filtros que reutilizan
